# # # # # # # # # # # # # # # # # # # # # #
# Author: Jun He
# Date: 09/2015
#
# This script is used to count the number of variants generated by samtools mpileup 
#
# Usage:
#    annotate_bam.py input_file output_file
#    
#    input_file: the output of samtools mpileup
#    output_file: The output file.
#
#
#
# Note: When the number of input arguments is not correct, an usage message will be printed on the screen.
#
# # # # # # # # # # # # # # # # # # # # # #

import sys,re

def annotate(pile,output):
    result = []
    
    f = open(pile)
    r = re.compile('[a-zA-Z]')
    for line in f:
        p = line[:-1].split('\t')
        p[4] = ''.join(r.findall(p[4]))
        result.append(p)
    f.close()
    
    result = sorted(result, key=lambda k:len(k[4]), reverse=True)
    
    f = open(output, 'w')
    for item in result:
        f.write('\t'.join(item) + '\n')
    
    f.close()
        


if __name__=='__main__':
    if len(sys.argv) != 3:
        print 'Invalid arguments'
        exit(1)
    
    annotate(sys.argv[1], sys.argv[2])
    print 'Finished successfully'